from api.configurations.algorithms.extraction import ExtractionAlgorithms
from api.configurations.algorithms.cleaning import CleaningAlgorithms
from api.configurations.algorithms.segmentation import SegmentationAlgorithms