from api.configurations.pipeline.extraction import ExtractionAlgorithms
from api.configurations.pipeline.cleaning import CleaningAlgorithms
from api.configurations.pipeline.segmentation import SegmentationAlgorithms
